In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded = files.upload()

import pandas as pd
filename = list(uploaded.keys())[0]   # get uploaded filename
df = pd.read_excel(filename) # Changed from pd.read_csv to pd.read_excel

print("Loaded:", filename)
#Display dataset structure (head, shape, datatypes)
df.head()

Saving Budget_vs_Actual_Data.xlsx to Budget_vs_Actual_Data (1).xlsx
Loaded: Budget_vs_Actual_Data (1).xlsx

,Date,Department,Category,Region,Budget Amount,Actual Amount,Payment Method,Transaction ID
0,2023-05-11,Sales,Travel,North,126096,43048,Card,TXN100000
1,2023-11-11,Marketing,Salaries,East,19702,87896,Bank Transfer,TXN100001
2,2021-05-02,IT,Training,Central,108523,103632,Card,TXN100002
3,2022-04-12,Marketing,Salaries,North,114711,105574,Cash,TXN100003
4,2021-11-27,Sales,Utilities,Central,121895,64314,UPI,TXN100004

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10010 entries, 0 to 10009
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            10010 non-null  datetime64[ns]
 1   Department      10009 non-null  object
 2   Category        10009 non-null  object
 3   Region          10007 non-null  object
 4   Budget Amount   10010 non-null  int64
 5   Actual Amount   10010 non-null  int64
 6   Payment Method  10010 non-null  object
 7   Transaction ID  10007 non-null  object
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 625.8+ KB

In [ ]:
df.describe()

                                Date  Budget Amount  Actual Amount
count                          10010   10010.000000   10010.000000
mean   2022-07-08 14:11:29.070928896   79531.584316   89031.239261
min              2021-01-01 00:00:00   10005.000000    8002.000000
25%              2021-10-08 00:00:00   44379.000000   48570.250000
50%              2022-07-12 00:00:00   79515.500000   89188.000000
75%              2023-04-09 00:00:00  114575.250000  130586.000000
max              2023-12-31 00:00:00  149992.000000  169973.000000
std                              NaN   40490.798172   46947.492216

DATA WRANGLING & CLEANING

In [ ]:
#Check missing values
df.isnull().sum()

Date              0
Department        1
Category          1
Region            3
Budget Amount     0
Actual Amount     0
Payment Method    0
Transaction ID    3
dtype: int64

In [ ]:
#Remove Duplicates
df.drop_duplicates()

,Date,Department,Category,Region,Budget Amount,Actual Amount,Payment Method,Transaction ID
0,2023-05-11,Sales,Travel,North,126096,43048,Card,TXN100000
1,2023-11-11,Marketing,Salaries,East,19702,87896,Bank Transfer,TXN100001
2,2021-05-02,IT,Training,Central,108523,103632,Card,TXN100002
3,2022-04-12,Marketing,Salaries,North,114711,105574,Cash,TXN100003
4,2021-11-27,Sales,Utilities,Central,121895,64314,UPI,TXN100004
...,...,...,...,...,...,...,...,...
9995,2022-09-05,Sales,Travel,South,60191,77111,Bank Transfer,TXN109995
9996,2022-11-28,Marketing,Marketing,East,123316,43319,Cash,TXN109996
9997,2022-08-26,IT,Salaries,West,106915,103450,UPI,TXN109997
9998,2021-09-05,Finance,Travel,East,99875,65338,Cash,TXN109998
9999,2021-12-25,Finance,Utilities,East,115870,38190,UPI,TXN109999

In [ ]:
# Handling Missing Values
df.dropna(inplace=True)
print('DataFrame after dropping rows with missing values:')
df.isnull().sum()

DataFrame after dropping rows with missing values:

Date              0
Department        0
Category          0
Region            0
Budget Amount     0
Actual Amount     0
Payment Method    0
Transaction ID    0
dtype: int64

In [ ]:
# Save the cleaned DataFrame to an Excel file
output_filename = 'cleaned_budget_vs_actual_data.xlsx'
df.to_excel(output_filename, index=False)

# Provide the file for download
from google.colab import files
files.download(output_filename)

print(f"Cleaned data saved to {output_filename} and is ready for download.")

Cleaned data saved to cleaned_budget_vs_actual_data.xlsx and is ready for download.